### ISSUE TITLE
'datetime.timedelta' object is not subscriptable

### ISSUE THREAD

**Issue by xianwenchen** [nomoketo/ttml2srt#1]
Hi!

I am trying to convert the attached ttml to srt. However, I got the following error: 

`Traceback (most recent call last):
  File "/home/chen/bin/ttml2srt.py", line 156, in <module>
    print(format_timestamp(timestamp)+' --> '+format_timestamp(rendered_grouped[i+1][0]))
TypeError: 'datetime.timedelta' object is not subscriptable
`

Could you advise how the error could be fixed?
[Spionligaen 1_52-MSUI47002110AA.no.ttml.zip](https://github.com/nomoketo/ttml2srt/files/868176/Spionligaen.1_52-MSUI47002110AA.no.ttml.zip)

**Comment by codingcatgirl** [comment]
Hi, thanks for your input! I just fixed it – the `Copyright (C) NRK` subtitle has `dur="00:00:00.000"` set. Because of this, a bug (fixed in 64eff70) caused this subtitle to be treated like it had no end time set at all which triggered another bug (fixed in ffdd9f3) that caused the script to crash if there were subtitles with no end time.
